config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  root 'items#index'
  post 'items/commission', to: 'items#commission'
  post 'items/profit', to: 'items#profit'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'personals', to: 'users/registrations#new_personal'
    post 'personals', to: 'users/registrations#create_personal'
  end

  resources :items do
    resources :purchases, only: [:index, :create]
  end
  resources :cards, only: [:new, :create, :destroy]
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :purchase_item, only: [:create, :pay_item]
  before_action :find_item, only: [:index, :move_to_root]
  before_action :move_to_login, only: [:index, :create]
  before_action :move_to_root, only: [:index, :create]

  def index
    @purchase = CardPurchase.new
    @card = Card.find_by(user_id: current_user.id)
  end
  
  def create
    @card = Card.find_by(user_id: current_user.id)
    @purchase = CardPurchase.new(purchase_params)
    if @purchase.valid?
      @purchase.save
      return redirect_to root_path
    else
      return render :index
    end
  end
  private
  
  def purchase_params
    params.permit(:token, :postal_code, :origin_area_id, :city, :house_number, :building_name, :phone_number).merge(user_id: current_user.id, item_id: params[:item_id])
  end
  
  def find_item
    @item = Item.find_by(id: params[:item_id])
  end

  def purchase_item
    @item = Item.find_by(id: purchase_params[:item_id])
  end

  def pay_item
    if current_user.card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer_token = current_user.card.customer_token
      Payjp::Charge.create(
        amount: @item.price,
        customer: customer_token,
        currency: "jpy"
      )
    else
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      Payjp::Charge.create(
        amount: @item.price,
        card: purchase_params[:token],
        currency: 'jpy'
      )
    end
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def move_to_root
    redirect_to root_path if current_user == @item.user
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/index.html.erb
<% breadcrumb :item_purchases, [@item, @purchase] %>
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <div class="purchase-images-box">  
          <% @item.images.each do |image| %>
            <div class="purchase-image">
              <%= image_tag  image , class: 'buy-item-img' %>
            </div>
          <% end %>
      </div>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.explain %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @item.price %></p>
          <p class='item-price-sub-text'>（税込）送料込み</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @item.price %>
      </p>
    </div>
    <%# /支払額の表示 %>
    <%= form_with url: item_purchases_path(@item, @purchase), method: :post, id: 'charge-form', class: 'transaction-form-wrap',local: true  do |f| %>
      <%= render partial: 'shared/error_messages', locals: {model: @purchase}  %>
      <%# カード情報の入力 %>
      <div class='credit-card-form'>
        <% unless @card.present? %>
          <h1 class='info-input-haedline'>
            クレジットカード情報入力
          </h1>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">カード情報</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
            <div class='available-card'>
              <%= image_tag 'card-visa.gif', class: 'card-logo'%>
              <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
              <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
              <%= image_tag 'card-amex.gif', class: 'card-logo'%>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">有効期限</label>
              <span class="indispensable">必須</span>
            </div>
            <div class='input-expiration-date-wrap'>
              <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
              <p>月</p>
              <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
              <p>年</p>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">セキュリティコード</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
          </div>
        <% else %>
          <div class="use-creditcard form-group">
            <p>登録済みのクレジットカードを使用する<p>
            <p>(再登録する場合は<%=link_to "こちら", card_path(@card), method: :delete ,local: true  %>)<p>
          </div>
        <% end %>
      </div>
      <%# /カード情報の入力 %>
      <%# 配送先の入力 %>

      <div class='shipping-address-form'>
        <h1 class='info-input-haedline'>
          配送先入力
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">郵便番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">都道府県</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:origin_area_id, OriginArea.all, :id, :name, {include_blank:"---"}, {class:"select-box", id:"prefecture"}) %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">市区町村</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">番地</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">建物名</label>
            <span class="form-any">任意</span>
          </div>
          <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">電話番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
        </div>
      </div> 

      <div class='buy-btn'>
        <%= f.submit "購入" ,class:"buy-red-btn", id:"purchase-submit" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>